### PR TITLE
Use peerDependencies in package.json instead of dependencies

### PR DESCRIPTION
**Pull request by richardpoole**
References:
- [How to write a loader](http://webpack.github.io/docs/how-to-write-a-loader.html#use-a-library-as-peerdependencies-when-they-wrap-it) (webpack docs)
- [Peer dependencies](http://blog.nodejs.org/2013/02/07/peer-dependencies/) (node.js blog)

### CODE REVIEW

**Comment by richardpoole** [comment]
Might be better to change the ractive version from `^0.5.6` to `~0` so it automatically picks up `0.6.x`, `0.7.x` etc. without needing an update (assuming the `Ractive.parse` API doesn't change)

**Comment by rstacruz** [comment]
Thanks! Will need to change that git url back though.

**Comment by rstacruz** [comment]
Merged, but not pushed to npm yet... will do that when I get to work on my laptop properly later :)

**Comment by rstacruz** [comment]
Also I've changed the ractive version to `~0`. (relevant-ish: http://ricostacruz.com/cheatsheets/semver)

**Comment by rstacruz** [comment]
Also added some tests btw... because why not. Thanks!

**Comment by richardpoole** [comment]
Awesome, thanks @rstacruz. And thanks @doctyper for fixing the problem. :)

**Pull request merged**
